export const config = {
  site: {
    name: 'Senscat',
    tagline: 'tiny products, fast experiments',
    domain: 'senscat.com',
    email: 'hanuljyw@naver.com',
  },
  services: [
    {
      id: 'picktube',
      name: 'PickTube',
      description: '유튜브 추천 커뮤니티',
      descriptionEn: 'YouTube recommendation community',
      url: 'https://picktube.senscat.com',
      icon: '📺',
    },
    {
      id: 'signal',
      name: 'Signal',
      description: '온라인 트렌드 다이제스트/요약',
      descriptionEn: 'Online trend digest & summaries',
      url: 'https://signal.senscat.com',
      icon: '📡',
    },
    {
      id: 'senslog',
      name: 'SensLog',
      description: '지식 기반 블로그',
      descriptionEn: 'Knowledge blog',
      url: 'https://senslog.senscat.com',
      icon: '📝',
    },
    {
      id: 'oneless',
      name: 'OneLess',
      description: '1인 개발자 포트폴리오 + 외주 문의',
      descriptionEn: 'Solo developer portfolio + inquiries',
      url: 'https://oneless.senscat.com',
      icon: '💼',
    },
  ],
  updates: [
    {
      date: '2026-02-10',
      title: '센스냥 런칭',
      titleEn: 'Senscat Launch',
      content: '1인 개발자 프로젝트 허브 센스냥(Senscat)을 공식적으로 런칭했습니다.',
      contentEn: 'Officially launched Senscat, an indie maker project hub.',
    },
    {
      date: '2026-02-05',
      title: 'Signal 프로토타입 완성',
      titleEn: 'Signal Prototype Complete',
      content: '웹 트렌드를 큐레이션하는 Signal 서비스의 프로토타입을 완성했습니다.',
      contentEn: 'Completed the prototype of Signal, a web trend digest service.',
    },
    {
      date: '2026-01-20',
      title: '센스냥 블로그 오픈',
      titleEn: 'Senscat Blog Launched',
      content: '개발과 프로덕트 실험을 기록하는 센스냥 블로그를 오픈했습니다.',
      contentEn: 'Launched the Senscat Blog to document development and product experiments.',
    },
    {
      date: '2026-01-12',
      title: 'PickTube 베타 오픈',
      titleEn: 'PickTube Beta Open',
      content: '유튜브 추천 커뮤니티 PickTube의 베타 서비스를 시작했습니다.',
      contentEn: 'Started the beta service for PickTube, a YouTube recommendation community.',
    },
    {
      date: '2026-01-01',
      title: 'OneLess 포트폴리오 공개',
      titleEn: 'OneLess Portfolio Launched',
      content: '1인 개발자 포트폴리오 OneLess를 공개하고 외주 개발 의뢰를 받기 시작했습니다.',
      contentEn: 'Launched the OneLess solo developer portfolio and started accepting freelance inquiries.',
    },
  ],
} as const;
