export const config = {
  site: {
    name: '센스냥',
    tagline: '디지털 서비스 기획·개발·운영',
    domain: 'senscat.com',
    email: 'sejabi@senscat.com',
  },
  seo: {
    keywordsKo: [
      '센스냥',
      'senscat',
      '센스AI',
      'SensAI',
      '센스에이아이',
      '센스매스',
      'Sensmath',
      'AI 수학',
      '중학생 수학',
      '기업 AI 분석',
      'AI 사용량 분석',
      'AI 구독 비용 최적화',
      '센스타로',
    ],
    keywordsEn: [
      'Senscat',
      'SensAI',
      '센스AI',
      'Sensmath',
      '센스매스',
      'AI math learning',
      'middle school math',
      'enterprise AI analytics',
      'AI usage analytics',
      'AI subscription optimization',
      'Senstaro',
    ],
  },
  company: {
    name: '센스냥(senscat)',
    ceo: '최정현',
    address: '경기도 의정부시 신흥로 234, 11층 스마트오피스',
    businessNumber: '589-20-02417',
    ecommerceRegistration: '2025-경기양주-0220',
    privacyOfficer: '최정현',
    email: 'sejabi@senscat.com',
  },
  services: [
    {
      id: 'sensmath',
      name: '센스매스',
      category: '교육 서비스',
      description: '센스매스(Sensmath)는 AI 기반 중학생 수학 진단·보충 학습 서비스입니다.',
      descriptionEn: 'Sensmath is an AI-based diagnostic and supplementary learning service for middle school math.',
      url: 'https://math.senscat.com',
      icon: 'SM',
      status: '운영',
      features: ['진단 평가', '보충 학습', '학습 데이터 기반 개선'],
    },
    {
      id: 'sensai',
      name: '센스AI',
      category: '기업 AI 분석',
      description: '센스AI(SensAI)는 기업 내 AI/LLM 사용 현황, 생산성, 구독 비용을 분석하는 관측·최적화 플랫폼입니다.',
      descriptionEn: 'SensAI is an enterprise AI and LLM usage observability, productivity analytics, and subscription optimization platform.',
      url: 'https://ai.senscat.com',
      icon: 'AI',
      status: '구축',
      features: ['AI 사용량 수집', '구독 비용 최적화', '관리자 대시보드'],
    },
    {
      id: 'senstaro',
      name: '센스타로',
      category: '상담 운영 도구',
      description: '타로 상담사가 카드 리딩을 생성·편집하고 고객에게 공유 링크로 전달하는 상담 지원 서비스',
      descriptionEn: 'Tarot consultation support service for creating, editing, and sharing AI-assisted readings',
      url: 'https://taro.senscat.com',
      icon: 'ST',
      status: '운영',
      features: ['AI 해석 보조', '공유 링크 전달', '상담 기록 관리'],
    },
  ],
  updates: [
    {
      date: '2026-03-16',
      title: '센스매스 런칭',
      titleEn: 'Sensmath Launch',
      content: 'AI기반 중학생 수학 진단·보충 학습 서비스 센스매스(Sensmath)를 공식적으로 런칭했습니다.',
      contentEn: 'Officially launched Sensmath, an AI-based diagnostic and supplementary learning service for middle school math.',
    },
  ],
} as const;
